# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/my-personal-blog',
                'doc_host': 'https://author31.github.io',
                'git_url': 'https://github.com/author31/my-personal-blog',
                'lib_path': 'my_personal_blog'},
  'syms': {}}
